[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32G474VETx "
linker = "flip-link"
rustflags = ["-Clink-arg=-Tlink.x"]

[build]
target = "thumbv7m-none-eabi"
