[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
egui_tiles = "0.10.1"
env_logger = "0.11.3"
log = "0.4.21"
nusb = "0.1.9"
foc = { path = "../../" }
fixed = { version = "1.28.0", features = ["std"] }
